#!/usr/bin/env bash

alacritty_dir=~/.config/alacritty
alacritty_file="$alacritty_dir"/alacritty.yml

mkdir -p $alacritty_dir
rm -rf $alacritty_file

ln -s $(pwd)/alacritty.yml $alacritty_file
# echo "-s $(pwd)/alacritty.yml $alacritty_file"
