# SEE: https://wiki.archlinux.org/title/Mpv
# SEE: https://kokomins.wordpress.com/2019/10/14/mpv-config-guide/
# SEE: https://github.com/noelsimbolon/mpv-config
# SEE: https://iamscum.wordpress.com/guides/videoplayback-guide/mpv-conf/
# SEE: https://thewiki.moe/tutorials/mpv/
# SEE: https://kohana.fi/article/mpv-for-anime
input-conf=~/.config/mpv/input.conf

screenshot-directory=~/Pictures/mpv-screenshots
screenshot-template="%F - [%P]" # Saved name template
screenshot-format=png # Set screenshot format.
volume=80 # Set default volume.
sub-auto=exact # Enable subtitles by default.
sub-codepage=auto # Set default subtitle encoding.
#autocreate-playlist=same # Generate a playlist from same files in the same directory.
loop=inf # loop=Number_of_repetitions.
osd-level=3 # Enable OSD (On Screen Display):
# - `0`: No OSD (completely disabled)
# - `1`: Minimal OSD (only essential information like volume, playback position)
# - `2`: Normal OSD (standard display with playback information)
# - `3`: Verbose OSD (full information including file details, playback stats, etc.)
osd-bar=no # No huge box on screen when turning the volume.
hwdec=auto-safe # [auto,auto-safe,no]: Enable hardware decoding.
vo=gpu-next # Enable smooth video playback.
gpu-api=vulkan #Or gpu-api=d3d11
ao=alsa # Set default audio device.
cache=auto # Valid values are: no, auto, yes.
# video-aspect-override=16:9 # Set default video aspect ratio.
save-position-on-quit=yes # Remember position when closing the player.

sub-auto=fuzzy
sub-font='Arial'
sub-font-size=40
sub-border-size=1
sub-shadow-color=0.0/0.0/0.0/0.50
sub-shadow-offset=2
