# General settings
input-conf=~/.config/mpv/input.conf
screenshot-directory=~/Pictures/mpv-screenshots

volume=80 # Set default volume
screenshot-format=png # Set screenshot format
sub-auto=exact # Enable subtitles by default
sub-codepage=auto # Set default subtitle encoding
## Enable OSD (On Screen Display):
# - `0`: No OSD (completely disabled)
# - `1`: Minimal OSD (only essential information like volume, playback position)
# - `2`: Normal OSD (standard display with playback information)
# - `3`: Verbose OSD (full information including file details, playback stats, etc.)
osd-level=2 
hwdec=auto # Enable hardware decoding
ao=alsa # Set default audio device
cache=auto # Valid values are: no, auto, yes
#vo=gpu # Enable smooth video playback
#video-aspect-override=16:9 # Set default video aspect ratio
